c_compiler:
  - clang  # [linux]
  - clang  # [osx]
  - vs2022  # [win]
c_compiler_version:  # [unix]
  - 22  # [linux]
  - 22  # [osx]
c_stdlib:
  - sysroot                     # [linux]
  - macosx_deployment_target    # [osx]
  - vs                          # [win]
cxx_compiler:
  - clangxx  # [linux]
  - vs2022  # [win]
  - clangxx  # [osx]
cxx_compiler_version:  # [unix]
  - 22  # [linux]
  - 22  # [osx]
